# Docker Compose file for the Battle Bot
#
# Usage:
#   docker compose build          # Build image
#   docker compose up -d          # Start container
#   docker exec -it bbot bash     # Shell into container
#
# Without an NVIDIA GPU:
#   docker compose -f docker-compose.yaml -f docker-compose.no-gpu.yaml up -d

services:
  cpu:
    image: bbot:latest
    container_name: bbot
    build:
      context: .
      dockerfile: docker/Dockerfile
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    privileged: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      # Default the ROS_DOMAIN_ID to zero
      - ROS_DOMAIN_ID=0
      # Allows graphical programs in the container
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Mount the source into the workspace to sync the container and host
      - ./bbot_description:/root/bbot_ws/src/bbot_description:rw
      - ./bbot_bringup:/root/bbot_ws/src/bbot_bringup:rw
      # Allow access to host hardware e.g. micro-controllers
      - /dev:/dev
      # Allows graphical programs in the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
